using System.Net;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using Moq;
using Moq.Protected;
using SwiftPantry.Web.Configuration;
using SwiftPantry.Web.Models;
using SwiftPantry.Web.Services;

namespace SwiftPantry.Tests.Services;

/// <summary>
/// Unit tests for LlmRecipeService.
/// All tests use a mock HttpMessageHandler — no real Gemini API calls are made.
/// </summary>
[TestFixture]
public class LlmRecipeServiceTests
{
    // ─── Helpers ─────────────────────────────────────────────────────────────

    /// <summary>Build a minimal valid Gemini JSON response envelope wrapping <paramref name="innerJson"/>.</summary>
    private static StringContent GeminiResponseEnvelope(string innerJson)
    {
        // Escape the inner JSON as a JSON string value
        var escapedInner = JsonSerializer.Serialize(innerJson); // produces "\"...\""
        var envelope = $$"""
            {
              "candidates": [
                {
                  "content": {
                    "role": "model",
                    "parts": [{ "text": {{escapedInner}} }]
                  }
                }
              ]
            }
            """;
        return new StringContent(envelope, Encoding.UTF8, "application/json");
    }

    /// <summary>Build a minimal valid recipe JSON that the service should accept.</summary>
    private static string ValidRecipeJson() => """
        {
          "name": "AI Test Chicken",
          "description": "A test recipe generated by Gemini.",
          "mealTypes": ["dinner"],
          "prepTimeMinutes": 20,
          "servings": 2,
          "caloriesPerServing": 450,
          "proteinPerServing": 40,
          "carbsPerServing": 30,
          "fatPerServing": 15,
          "ingredients": [
            { "name": "chicken breast", "quantity": "1 lb", "category": "Protein" },
            { "name": "olive oil", "quantity": "2 tbsp", "category": "PantryStaples" },
            { "name": "garlic", "quantity": "3 cloves", "category": "Produce" }
          ],
          "instructions": [
            "Step 1: Season the chicken.",
            "Step 2: Heat olive oil in a pan.",
            "Step 3: Cook chicken until done."
          ]
        }
        """;

    /// <summary>Create a service backed by the given mock handler, configuration key, and feature flag.</summary>
    private static LlmRecipeService CreateService(
        Mock<HttpMessageHandler> handlerMock,
        string apiKey = "test-api-key",
        bool featureEnabled = true,
        int timeoutSeconds = 30)
    {
        var httpClient = new HttpClient(handlerMock.Object)
        {
            Timeout = TimeSpan.FromSeconds(timeoutSeconds)
        };

        var options = Options.Create(new GeminiOptions
        {
            ApiKey          = apiKey,
            Model           = "gemini-2.0-flash",
            MaxOutputTokens = 4096
        });

        var config = new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["Features:EnableLlmRecipes"] = featureEnabled.ToString().ToLower()
            })
            .Build();

        return new LlmRecipeService(httpClient, options, config, NullLogger<LlmRecipeService>.Instance);
    }

    // ─── IsAvailable ─────────────────────────────────────────────────────────

    [Test]
    public void IsAvailable_FeatureFlagOff_ReturnsFalse()
    {
        var handler = new Mock<HttpMessageHandler>();
        var sut = CreateService(handler, apiKey: "some-key", featureEnabled: false);

        Assert.That(sut.IsAvailable, Is.False);
    }

    [Test]
    public void IsAvailable_FeatureFlagOn_NoApiKey_ReturnsFalse()
    {
        var handler = new Mock<HttpMessageHandler>();
        var sut = CreateService(handler, apiKey: "", featureEnabled: true);

        Assert.That(sut.IsAvailable, Is.False);
    }

    [Test]
    public void IsAvailable_FeatureFlagOn_ApiKeyPresent_ReturnsTrue()
    {
        var handler = new Mock<HttpMessageHandler>();
        var sut = CreateService(handler, apiKey: "valid-key", featureEnabled: true);

        Assert.That(sut.IsAvailable, Is.True);
    }

    // ─── Prompt construction / request body ──────────────────────────────────

    [Test]
    public async Task GenerateRecipeAsync_SendsCorrectRequestBody()
    {
        HttpRequestMessage? capturedRequest = null;

        var handler = new Mock<HttpMessageHandler>();
        handler
            .Protected()
            .Setup<Task<HttpResponseMessage>>(
                "SendAsync",
                ItExpr.IsAny<HttpRequestMessage>(),
                ItExpr.IsAny<CancellationToken>())
            .Callback<HttpRequestMessage, CancellationToken>((req, _) => capturedRequest = req)
            .ReturnsAsync(new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = GeminiResponseEnvelope(ValidRecipeJson())
            });

        var sut = CreateService(handler);
        var request = new RecipeGenerationRequest
        {
            PantryIngredients  = new List<string> { "chicken breast", "olive oil" },
            MealType           = "dinner",
            MaxPrepTimeMinutes = 30,
            DailyCalorieTarget = 2000,
            ProteinTargetGrams = 150
        };

        await sut.GenerateRecipeAsync(request);

        Assert.That(capturedRequest, Is.Not.Null);

        var bodyJson = await capturedRequest!.Content!.ReadAsStringAsync();

        // Request should include the pantry ingredients in the prompt
        Assert.That(bodyJson, Does.Contain("chicken breast"),
            "Request body should reference pantry items");

        // Request should include the meal type
        Assert.That(bodyJson, Does.Contain("dinner"),
            "Request body should reference the meal type");

        // Request should include the calorie target
        Assert.That(bodyJson, Does.Contain("2000"),
            "Request body should reference the calorie target");

        // Request should include responseMimeType = application/json
        Assert.That(bodyJson, Does.Contain("application/json"),
            "Request body should request JSON response MIME type");
    }

    [Test]
    public async Task GenerateRecipeAsync_UsesApiKeyInUrl()
    {
        Uri? capturedUri = null;

        var handler = new Mock<HttpMessageHandler>();
        handler
            .Protected()
            .Setup<Task<HttpResponseMessage>>(
                "SendAsync",
                ItExpr.IsAny<HttpRequestMessage>(),
                ItExpr.IsAny<CancellationToken>())
            .Callback<HttpRequestMessage, CancellationToken>((req, _) => capturedUri = req.RequestUri)
            .ReturnsAsync(new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = GeminiResponseEnvelope(ValidRecipeJson())
            });

        var sut = CreateService(handler, apiKey: "my-secret-key");
        await sut.GenerateRecipeAsync(new RecipeGenerationRequest());

        Assert.That(capturedUri?.Query, Does.Contain("key=my-secret-key"),
            "API key must be passed as a query parameter");
    }

    // ─── Response parsing ─────────────────────────────────────────────────────

    [Test]
    public async Task GenerateRecipeAsync_ValidResponse_ReturnsPopulatedRecipe()
    {
        var handler = new Mock<HttpMessageHandler>();
        handler
            .Protected()
            .Setup<Task<HttpResponseMessage>>(
                "SendAsync",
                ItExpr.IsAny<HttpRequestMessage>(),
                ItExpr.IsAny<CancellationToken>())
            .ReturnsAsync(new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = GeminiResponseEnvelope(ValidRecipeJson())
            });

        var sut = CreateService(handler);
        var recipe = await sut.GenerateRecipeAsync(new RecipeGenerationRequest());

        Assert.That(recipe, Is.Not.Null);
        Assert.That(recipe!.Name, Is.EqualTo("AI Test Chicken"));
        Assert.That(recipe.Description, Is.EqualTo("A test recipe generated by Gemini."));
        Assert.That(recipe.MealTypes, Is.EqualTo("dinner"));
        Assert.That(recipe.PrepTimeMinutes, Is.EqualTo(20));
        Assert.That(recipe.DefaultServings, Is.EqualTo(2));
        Assert.That(recipe.CaloriesPerServing, Is.EqualTo(450));
        Assert.That(recipe.ProteinPerServing, Is.EqualTo(40m));
        Assert.That(recipe.CarbsPerServing, Is.EqualTo(30m));
        Assert.That(recipe.FatPerServing, Is.EqualTo(15m));
        Assert.That(recipe.Ingredients, Has.Count.EqualTo(3));
        Assert.That(recipe.InstructionList, Has.Count.EqualTo(3));
        Assert.That(recipe.IsUserCreated, Is.True);
        Assert.That(recipe.Id, Is.EqualTo(-1), "LLM recipe should have temporary Id=-1");
    }

    [Test]
    public async Task GenerateRecipeAsync_IngredientsNormalizedToLowercase()
    {
        var recipeJson = """
            {
              "name": "Test",
              "description": "desc",
              "mealTypes": ["lunch"],
              "prepTimeMinutes": 10,
              "servings": 1,
              "caloriesPerServing": 300,
              "proteinPerServing": 20,
              "carbsPerServing": 30,
              "fatPerServing": 10,
              "ingredients": [{ "name": "CHICKEN BREAST", "quantity": "1 lb", "category": "Protein" }],
              "instructions": ["Step 1.", "Step 2."]
            }
            """;

        var handler = new Mock<HttpMessageHandler>();
        handler
            .Protected()
            .Setup<Task<HttpResponseMessage>>(
                "SendAsync",
                ItExpr.IsAny<HttpRequestMessage>(),
                ItExpr.IsAny<CancellationToken>())
            .ReturnsAsync(new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = GeminiResponseEnvelope(recipeJson)
            });

        var sut = CreateService(handler);
        var recipe = await sut.GenerateRecipeAsync(new RecipeGenerationRequest());

        Assert.That(recipe!.Ingredients.First().Name, Is.EqualTo("chicken breast"),
            "Ingredient names should be normalized to lowercase");
    }

    // ─── Error handling ───────────────────────────────────────────────────────

    [Test]
    public async Task GenerateRecipeAsync_RateLimited_ReturnsNull()
    {
        var handler = new Mock<HttpMessageHandler>();
        handler
            .Protected()
            .Setup<Task<HttpResponseMessage>>(
                "SendAsync",
                ItExpr.IsAny<HttpRequestMessage>(),
                ItExpr.IsAny<CancellationToken>())
            .ReturnsAsync(new HttpResponseMessage(HttpStatusCode.TooManyRequests));

        var sut = CreateService(handler);
        var recipe = await sut.GenerateRecipeAsync(new RecipeGenerationRequest());

        Assert.That(recipe, Is.Null);
    }

    [Test]
    public async Task GenerateRecipeAsync_MalformedJson_ReturnsNull()
    {
        var handler = new Mock<HttpMessageHandler>();
        handler
            .Protected()
            .Setup<Task<HttpResponseMessage>>(
                "SendAsync",
                ItExpr.IsAny<HttpRequestMessage>(),
                ItExpr.IsAny<CancellationToken>())
            .ReturnsAsync(new HttpResponseMessage(HttpStatusCode.OK)
            {
                // Garbage JSON — not valid Gemini envelope at all
                Content = new StringContent("this is not json", Encoding.UTF8, "application/json")
            });

        var sut = CreateService(handler);
        var recipe = await sut.GenerateRecipeAsync(new RecipeGenerationRequest());

        Assert.That(recipe, Is.Null);
    }

    [Test]
    public async Task GenerateRecipeAsync_MalformedRecipeJson_ReturnsNull()
    {
        var handler = new Mock<HttpMessageHandler>();
        handler
            .Protected()
            .Setup<Task<HttpResponseMessage>>(
                "SendAsync",
                ItExpr.IsAny<HttpRequestMessage>(),
                ItExpr.IsAny<CancellationToken>())
            .ReturnsAsync(new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = GeminiResponseEnvelope("{not valid json {{")
            });

        var sut = CreateService(handler);
        var recipe = await sut.GenerateRecipeAsync(new RecipeGenerationRequest());

        Assert.That(recipe, Is.Null);
    }

    [Test]
    public async Task GenerateRecipeAsync_Timeout_ReturnsNull()
    {
        var handler = new Mock<HttpMessageHandler>();
        handler
            .Protected()
            .Setup<Task<HttpResponseMessage>>(
                "SendAsync",
                ItExpr.IsAny<HttpRequestMessage>(),
                ItExpr.IsAny<CancellationToken>())
            .Returns<HttpRequestMessage, CancellationToken>(async (_, ct) =>
            {
                // Delay longer than the 1ms timeout we configure below
                await Task.Delay(200, ct);
                return new HttpResponseMessage(HttpStatusCode.OK);
            });

        // 1ms timeout will fire before the 200ms delay
        var httpClient = new HttpClient(handler.Object) { Timeout = TimeSpan.FromMilliseconds(1) };
        var options = Options.Create(new GeminiOptions { ApiKey = "test", Model = "gemini-2.0-flash" });
        var config = new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?> { ["Features:EnableLlmRecipes"] = "true" })
            .Build();

        var sut = new LlmRecipeService(httpClient, options, config, NullLogger<LlmRecipeService>.Instance);
        var recipe = await sut.GenerateRecipeAsync(new RecipeGenerationRequest());

        Assert.That(recipe, Is.Null);
    }

    [Test]
    public async Task GenerateRecipeAsync_EmptyRecipeName_ReturnsNull()
    {
        var badRecipeJson = """
            {
              "name": "",
              "description": "desc",
              "mealTypes": ["lunch"],
              "prepTimeMinutes": 10,
              "servings": 2,
              "caloriesPerServing": 300,
              "proteinPerServing": 20,
              "carbsPerServing": 30,
              "fatPerServing": 10,
              "ingredients": [{ "name": "egg", "quantity": "2", "category": "Protein" }],
              "instructions": ["Step 1.", "Step 2."]
            }
            """;

        var handler = new Mock<HttpMessageHandler>();
        handler
            .Protected()
            .Setup<Task<HttpResponseMessage>>(
                "SendAsync",
                ItExpr.IsAny<HttpRequestMessage>(),
                ItExpr.IsAny<CancellationToken>())
            .ReturnsAsync(new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = GeminiResponseEnvelope(badRecipeJson)
            });

        var sut = CreateService(handler);
        var recipe = await sut.GenerateRecipeAsync(new RecipeGenerationRequest());

        Assert.That(recipe, Is.Null, "Empty name should fail validation");
    }

    [Test]
    public async Task GenerateRecipeAsync_ZeroCalories_ReturnsNull()
    {
        var badRecipeJson = """
            {
              "name": "Zero Cal Soup",
              "description": "desc",
              "mealTypes": ["lunch"],
              "prepTimeMinutes": 10,
              "servings": 2,
              "caloriesPerServing": 0,
              "proteinPerServing": 5,
              "carbsPerServing": 5,
              "fatPerServing": 1,
              "ingredients": [{ "name": "water", "quantity": "1 cup", "category": "Other" }],
              "instructions": ["Boil water.", "Serve."]
            }
            """;

        var handler = new Mock<HttpMessageHandler>();
        handler
            .Protected()
            .Setup<Task<HttpResponseMessage>>(
                "SendAsync",
                ItExpr.IsAny<HttpRequestMessage>(),
                ItExpr.IsAny<CancellationToken>())
            .ReturnsAsync(new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = GeminiResponseEnvelope(badRecipeJson)
            });

        var sut = CreateService(handler);
        var recipe = await sut.GenerateRecipeAsync(new RecipeGenerationRequest());

        Assert.That(recipe, Is.Null, "Zero calories should fail validation");
    }

    [Test]
    public async Task GenerateRecipeAsync_FeatureFlagOff_ReturnsNullWithoutCallingApi()
    {
        var handler = new Mock<HttpMessageHandler>();
        handler
            .Protected()
            .Setup<Task<HttpResponseMessage>>(
                "SendAsync",
                ItExpr.IsAny<HttpRequestMessage>(),
                ItExpr.IsAny<CancellationToken>())
            .ReturnsAsync(new HttpResponseMessage(HttpStatusCode.OK));

        var sut = CreateService(handler, featureEnabled: false);
        var recipe = await sut.GenerateRecipeAsync(new RecipeGenerationRequest());

        Assert.That(recipe, Is.Null);

        // API must NOT be called
        handler.Protected().Verify(
            "SendAsync",
            Times.Never(),
            ItExpr.IsAny<HttpRequestMessage>(),
            ItExpr.IsAny<CancellationToken>());
    }

    [Test]
    public async Task GenerateRecipeAsync_NetworkError_ReturnsNull()
    {
        var handler = new Mock<HttpMessageHandler>();
        handler
            .Protected()
            .Setup<Task<HttpResponseMessage>>(
                "SendAsync",
                ItExpr.IsAny<HttpRequestMessage>(),
                ItExpr.IsAny<CancellationToken>())
            .ThrowsAsync(new HttpRequestException("Network failure"));

        var sut = CreateService(handler);
        var recipe = await sut.GenerateRecipeAsync(new RecipeGenerationRequest());

        Assert.That(recipe, Is.Null);
    }
}
